### PR TITLE
docker lunch

### PR DESCRIPTION
**Pull request by diegogub**
Hi, I'm trying to add Docker support. I suggest to do it this way. 

I'm not sure if exposing all ports should be good. It might me better to keep all close, but let me know what you think.

Thanks!

### CODE REVIEW

**Comment by neunhoef** [comment]
The patch in its current form installs the complete go distribution into the container image just to compile a single source file. I would suggest not to not this. I would make a Dockerfile which assumes that the executable is compiled for the architecture used in the arangodb Docker image (Debian jessie, I believe). It is straightforward (with something like your Dockerfile) to produce such a binary and then use a much simpler Dockerfile to make the finished product. The image size should be dramatically smaller, it will work as well, since a go executable does not need the go distribution installed. What do you think?

**Comment by diegogub** [comment]
Hello @neunhoef , yes, I know what you mean. The only issue is that makes the docker building process depend on the local computer, but could be done with a Makefile and cross compiling for sure.
but it will keep image much smaller. I will try do it and push it!

**Comment by diegogub** [comment]
@neunhoef now the image is small as arangodb:latest :smile: , please review
we could also change the tag name..

**Comment by neunhoef** [comment]
Great, thanks. I will try to add a way to build the debian/jessie executable in another Docker container when I find time.

**Comment by neunhoef** [comment]
See comments in the issue about Docker support. In short: It is not yet working correctly.

**Comment by diegogub** [comment]
@neunhoef , ok thanks!. I have just deploy a cluster in using rancher (http://rancher.com/) and this image. It's working good! thanks

**Comment by diegogub** [comment]
I will be working in making an arangodb catalog image : http://docs.rancher.com/rancher/v1.3/en/catalog/

**Comment by neunhoef** [comment]
Fantastic! I would be interested on the details of how you got this to
work!

Cheers,
  Max.

**Pull request merged**
